apiVersion: v1
kind: Service
metadata:
  name: fullstack-app
  namespace: fullstack
  labels:
    app: fullstack-app
spec:
  selector:
    app: fullstack-app
  ports:
    - name: http
      port: 80
      targetPort: 3009
